services:
  hytale:
    image: gamedevllama/hytale-server
    container_name: hytale-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "5520:5520/udp"
    volumes:
      - /docker/storage/hytale/data:/data
      - /docker/storage/hytale/assets:/assets
    environment:
      JAVA_OPTS: "-Dio.netty.transport.noNative=true"
      HYTALE_OPTS: ""
      ASSETS_AUTO_UPDATE: "false"
      # ASSETS_PATCHLINE: "pre-release"
